/**
 * screen_dice.cpp - Random Dice app
 */
#include "screen_dice.h"
#include "app_manager.h"
#include "ui_theme.h"
#include "i18n.h"
#include "png_assets.h"
#include "settings.h"
#include <M5Unified.h>
#include <stdlib.h>
#include <esp_random.h>
#include "dice_wav.h"

#define MAX_DICE 3
#define ROLL_FRAMES 13
#define ROLL_LOOPS 2
#define FRAME_DELAY 66

/* Image descriptors generated by pre_build.py */
extern const lv_img_dsc_t img_dice_anim_0_png;
extern const lv_img_dsc_t img_dice_anim_1_png;
extern const lv_img_dsc_t img_dice_anim_2_png;
extern const lv_img_dsc_t img_dice_anim_3_png;
extern const lv_img_dsc_t img_dice_anim_4_png;
extern const lv_img_dsc_t img_dice_anim_5_png;
extern const lv_img_dsc_t img_dice_anim_6_png;
extern const lv_img_dsc_t img_dice_anim_7_png;
extern const lv_img_dsc_t img_dice_anim_8_png;
extern const lv_img_dsc_t img_dice_anim_9_png;
extern const lv_img_dsc_t img_dice_anim_10_png;
extern const lv_img_dsc_t img_dice_anim_11_png;
extern const lv_img_dsc_t img_dice_anim_12_png;

extern const lv_img_dsc_t img_dice_res_1_png;
extern const lv_img_dsc_t img_dice_res_2_png;
extern const lv_img_dsc_t img_dice_res_3_png;
extern const lv_img_dsc_t img_dice_res_4_png;
extern const lv_img_dsc_t img_dice_res_5_png;
extern const lv_img_dsc_t img_dice_res_6_png;

static const lv_img_dsc_t* anim_frames[ROLL_FRAMES] = {
    &img_dice_anim_0_png, &img_dice_anim_1_png, &img_dice_anim_2_png,
    &img_dice_anim_3_png, &img_dice_anim_4_png, &img_dice_anim_5_png,
    &img_dice_anim_6_png, &img_dice_anim_7_png, &img_dice_anim_8_png,
    &img_dice_anim_9_png, &img_dice_anim_10_png, &img_dice_anim_11_png,
    &img_dice_anim_12_png
};

static const lv_img_dsc_t* res_frames[6] = {
    &img_dice_res_1_png, &img_dice_res_2_png, &img_dice_res_3_png,
    &img_dice_res_4_png, &img_dice_res_5_png, &img_dice_res_6_png
};

static lv_obj_t *root = NULL;
static lv_obj_t *dice_imgs[MAX_DICE];
static lv_timer_t *anim_timer = NULL;
static lv_timer_t *input_timer = NULL;

static int dice_count = 1;
static bool is_rolling = false;
static int anim_step = 0;
static int target_loops = 0;

static void layout_dice() {
    for (int i = 0; i < MAX_DICE; i++) {
        if (i < dice_count) {
            lv_obj_clear_flag(dice_imgs[i], LV_OBJ_FLAG_HIDDEN);
        } else {
            lv_obj_add_flag(dice_imgs[i], LV_OBJ_FLAG_HIDDEN);
        }
    }

    if (dice_count == 1) {
        lv_obj_align(dice_imgs[0], LV_ALIGN_CENTER, 0, 0);
    } else if (dice_count == 2) {
        lv_obj_align(dice_imgs[0], LV_ALIGN_CENTER, 0, -40);
        lv_obj_align(dice_imgs[1], LV_ALIGN_CENTER, 0, 40);
    } else if (dice_count == 3) {
        lv_obj_align(dice_imgs[0], LV_ALIGN_CENTER, 0, -45);
        lv_obj_align(dice_imgs[1], LV_ALIGN_CENTER, -35, 30);
        lv_obj_align(dice_imgs[2], LV_ALIGN_CENTER, 35, 30);
    }
}

static void play_dice_sound() {
    int vol_map[4] = {0, 64, 128, 200};
    int vol = settings_get()->sys_volume;
    if (vol > 0) {
        M5.Speaker.setVolume(vol_map[vol]);
        M5.Speaker.playWav(dice_wav, dice_wav_len);
    }
}

static void roll_anim_cb(lv_timer_t * t) {
    if (!is_rolling) return;

    if (anim_step == 0 && target_loops == ROLL_LOOPS) {
        play_dice_sound();
    }

    for (int i = 0; i < dice_count; i++) {
        // Random offset for each dice to make them look different while rolling
        int frame_idx = (anim_step + i * 3) % ROLL_FRAMES;
        lv_img_set_src(dice_imgs[i], anim_frames[frame_idx]);
    }

    anim_step++;
    if (anim_step >= ROLL_FRAMES) {
        anim_step = 0;
        target_loops--;
        if (target_loops <= 0) {
            // Stop rolling
            is_rolling = false;
            for (int i = 0; i < dice_count; i++) {
                int res = esp_random() % 6; // 0-5
                lv_img_set_src(dice_imgs[i], res_frames[res]);
            }
            lv_timer_pause(anim_timer);
        }
    }
}

static void start_roll() {
    if (is_rolling) return;
    is_rolling = true;
    anim_step = 0;
    target_loops = ROLL_LOOPS;
    lv_timer_resume(anim_timer);
}

static void input_timer_cb(lv_timer_t * t) {
    input_event_t ev = app_manager_get_input();
    
    // Check IMU for shake
    float ax, ay, az;
    M5.Imu.getAccel(&ax, &ay, &az);
    if (!is_rolling && (abs(ax) > 1.8f || abs(ay) > 1.8f || abs(az) > 1.8f)) {
        start_roll();
    }

    if (ev == INPUT_BACK) {
        app_manager_show_menu();
        return;
    }

    if (ev == INPUT_CONFIRM) {
        start_roll();
    } else if (ev == INPUT_NEXT && !is_rolling) {
        dice_count++;
        if (dice_count > MAX_DICE) dice_count = 1;
        layout_dice();
        
        // Reset faces to random static
        for (int i = 0; i < dice_count; i++) {
            int res = esp_random() % 6;
            lv_img_set_src(dice_imgs[i], res_frames[res]);
        }
    }
}

extern "C" void screen_dice_create(lv_obj_t *parent) {
    root = parent;
    
    lv_obj_t *title = lv_label_create(root);
    lv_obj_set_style_text_font(title, &lv_font_cn_16, 0);
    lv_obj_set_style_text_color(title, COLOR_TEXT, 0);
    lv_label_set_text(title, i18n_str(STR_DICE));
    lv_obj_align(title, LV_ALIGN_TOP_MID, 0, 20);

    for (int i = 0; i < MAX_DICE; i++) {
        dice_imgs[i] = lv_img_create(root);
        int res = esp_random() % 6;
        lv_img_set_src(dice_imgs[i], res_frames[res]);
    }

    dice_count = 1;
    layout_dice();

    is_rolling = false;
    anim_timer = lv_timer_create(roll_anim_cb, FRAME_DELAY, NULL);
    lv_timer_pause(anim_timer);
    
    input_timer = lv_timer_create(input_timer_cb, 50, NULL);
}

extern "C" void screen_dice_destroy(void) {
    if (anim_timer) {
        lv_timer_del(anim_timer);
        anim_timer = NULL;
    }
    if (input_timer) {
        lv_timer_del(input_timer);
        input_timer = NULL;
    }
    root = NULL;
}
